name: Endpoints

on:
  push:
    branches: ["master"]

jobs:
  document-to-html:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source files
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install grip
    - name: Document to HTML
      run: |
        cd src/standards/endpoints/1.0/
        grip document.md --wide --title="Endpoints 1.0" --export
    - name: Upload the HTML document
      uses: actions/upload-artifact@v3
      with:
        name: endpoints-html-version
        path: src/standards/endpoints/1.0/document.html

  schema-test-suite:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source files
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pyyaml jsonschema
    - name: Run test suite
      run: |
        cd src/standards/endpoints/1.0/tests/schema/
        pytest
